### ISSUE TITLE
auto-scale

### ISSUE THREAD

**Issue by delanym** [shokinn/docker-alpine-desktop#2]
Auto-scale does nothing and the resolution stays about 1024. I'm on Firefox

**Comment by shokinn** [comment]
I'm pretty sure this is based on the base image I use.
Try to build the Docker image by your own and update the Base image (https://github.com/jlesage/docker-baseimage-gui)

I currently don't have the time to look into it.

But if you can fix it, I'm happy to accept an PR.

**Comment by delanym** [comment]
Ok I set the DISPLAY_WIDTH and DISPLAY_HEIGHT env vars to 1920x1080 which was my main issue. It seems auto-scale scales down, not up.
